name: CI/CD Pipeline
 
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
 
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}
  GAR_LOCATION: us-central1
  REPO_NAME: ai-financial-advisor
  SERVICE_NAME: ai-financial-advisor
  REGION: us-central1
  IMAGE: ${{ secrets.GCP_PROJECT_ID }}.us-central1-docker.pkg.dev/ai-financial-advisor/ai-financial-advisor
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
 
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
 
      - name: Run Tests
        run: pytest test.py
 
      - name: Lint Code
        run: |
          pip install black flake8
          black . --check
          flake8 .
 
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ env.SERVICE_ACCOUNT_KEY }}
 
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
 
      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet
 
      - name: Build Docker Image
        run: docker build -t $IMAGE:$GITHUB_SHA .
 
      - name: Push Docker Image to Artifact Registry
        run: docker push $IMAGE:$GITHUB_SHA
 
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image $IMAGE:$GITHUB_SHA \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated